name: Build AsciiDoc PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Asciidoctor PDF
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full

          gem install --user-install asciidoctor
          gem install --user-install asciidoctor-pdf

          # Ruby ermittelt automatisch den richtigen Pfad
          GEM_BIN_DIR="$(ruby -e 'print Gem.user_dir')/bin"

          echo "$GEM_BIN_DIR" >> $GITHUB_PATH
          echo "GEM_BIN_DIR=$GEM_BIN_DIR"  # Debug-Ausgabe

      - name: Build PDF
        run: |
          asciidoctor-pdf -a pdf-page-layout=landscape -a pdf-theme=theme.yml hamradio_activity_cheat_sheet_de.adoc

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: hamradio-activity-cheat-sheet-de-pdf
          path: hamradio_activity_cheat_sheet_de.pdf

